# Generated by Django 5.2.4 on 2025-08-08 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('requisition', 'Job Requisition'), ('policy', 'Policy Update'), ('compliance', 'Compliance Alert'), ('case', 'HR Case')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hr_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HRDashboard',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_headcount', models.IntegerField(default=0)),
                ('open_requisitions', models.IntegerField(default=0)),
                ('high_priority_cases', models.IntegerField(default=0)),
                ('compliance_alerts', models.IntegerField(default=0)),
                ('turnover_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_hire_time', models.IntegerField(default=0)),
                ('satisfaction_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('budget_utilization', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='departmentid', on_delete=django.db.models.deletion.CASCADE, to='panel.departments')),
            ],
            options={
                'db_table': 'hr_dashboard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HRPolicy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_policies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('requisition_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary_range', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='departmentid', on_delete=django.db.models.deletion.CASCADE, to='panel.departments')),
                ('requested_by', models.ForeignKey(db_column='requested_by', on_delete=django.db.models.deletion.CASCADE, related_name='requested_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_requisitions',
                'managed': True,
            },
        ),
    ]
