# Generated by Django 5.2.4 on 2025-10-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_of_human_resources', '0002_financialreport_budgetadjustmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number for payments', max_length=50, null=True),
        ),
    ]
