# Generated by Django 5.2.4 on 2025-10-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_of_human_resources', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly allowance amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current overtime amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Monthly base salary', max_digits=10),
        ),
    ]
