# Generated by Django 5.2.4 on 2025-10-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_of_human_resources', '0005_employee_allowance_employee_overtime_and_more'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='hod_of_human_resources.employee')),
            ],
            options={
                'db_table': 'disputes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('readiness', models.CharField(choices=[('ready', 'Ready'), ('developing', 'Developing'), ('future', 'Future')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_plans', to='hod_of_human_resources.employee')),
            ],
            options={
                'db_table': 'succession_plans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkforcePlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('headcount_needed', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='departmentid', on_delete=django.db.models.deletion.CASCADE, to='panel.departments')),
            ],
            options={
                'db_table': 'workforce_plans',
                'managed': True,
            },
        ),
    ]
