# Generated by Django 5.2.4 on 2025-10-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod_of_human_resources', '0007_meeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrnotification',
            options={'managed': True},
        ),
    ]
