# Generated by Django 5.2.4 on 2025-10-27 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_of_human_resources', '0008_alter_hrnotification_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('requisition', 'Job Requisition'), ('policy', 'Policy Update'), ('compliance', 'Compliance Alert'), ('case', 'HR Case'), ('meeting', 'Meeting')], max_length=20)),
                ('recipient', models.ForeignKey(db_column='recipient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_notifications', to=settings.AUTH_USER_MODEL)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hr_notification',
                'managed': True,
            },
        ),
    ]
