# Generated by Django 5.2.4 on 2025-10-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_of_human_resources', '0009_hrnotification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrpolicy',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF document', null=True, upload_to='hr_policies/'),
        ),
    ]
