# Generated by Django 5.2.4 on 2025-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hod_graphics', 'Head of Graphics'), ('hod_human_resources', 'Head of Human Resources'), ('head_of_department', 'Head of Department'), ('staff', 'Staff'), ('system_developer', 'System Developer')], max_length=50),
        ),
    ]
