# Generated by Django 5.2.4 on 2025-08-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('addressid', models.AutoField(primary_key=True, serialize=False)),
                ('entitytype', models.CharField(blank=True, max_length=50, null=True)),
                ('entityid', models.IntegerField(blank=True, null=True)),
                ('addresstype', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointmentid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('location_url', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('checkintime', models.TimeField(blank=True, null=True)),
                ('checkouttime', models.TimeField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('tablename', models.CharField(blank=True, max_length=255, null=True)),
                ('recordid', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('billid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billtype', models.CharField(blank=True, max_length=255, null=True)),
                ('billdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('budgetid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'budgets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('accountid', models.AutoField(primary_key=True, serialize=False)),
                ('accountname', models.CharField(blank=True, max_length=255, null=True)),
                ('accounttype', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chart_of_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistItems',
            fields=[
                ('checklistitemid', models.AutoField(primary_key=True, serialize=False)),
                ('itemtext', models.TextField(blank=True, null=True)),
                ('itemorder', models.IntegerField(blank=True, null=True)),
                ('itemtype', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'checklist_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checklists',
            fields=[
                ('checklistid', models.AutoField(primary_key=True, serialize=False)),
                ('checklistname', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checklists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecords',
            fields=[
                ('compliancerecordid', models.AutoField(primary_key=True, serialize=False)),
                ('certificatename', models.CharField(blank=True, max_length=255, null=True)),
                ('issuingbody', models.CharField(blank=True, max_length=255, null=True)),
                ('issuedate', models.DateField(blank=True, null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
                ('documentpath', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'compliance_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCommunications',
            fields=[
                ('communicationid', models.AutoField(primary_key=True, serialize=False)),
                ('communicationtype', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('communicationtimestamp', models.DateTimeField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_communications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=255)),
                ('contactperson', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departmentid', models.AutoField(primary_key=True, serialize=False)),
                ('departmentname', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('documentid', models.AutoField(primary_key=True, serialize=False)),
                ('filepath', models.CharField(blank=True, max_length=255, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('documenttype', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('employeeskillid', models.AutoField(primary_key=True, serialize=False)),
                ('proficiencylevel', models.CharField(blank=True, max_length=50, null=True)),
                ('lastverifieddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialTransactions',
            fields=[
                ('transactionid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financial_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrCases',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('casetype', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('dateopened', models.DateField(blank=True, null=True)),
                ('dateclosed', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryid', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryMovements',
            fields=[
                ('movementid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_movements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgebaseArticles',
            fields=[
                ('articleid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('ispublic', models.BooleanField(blank=True, null=True)),
                ('categoryid', models.IntegerField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knowledgebase_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('leadid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('leaveid', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leave_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaigns',
            fields=[
                ('campaignid', models.AutoField(primary_key=True, serialize=False)),
                ('campaignname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketing_campaigns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('orderitemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, null=True)),
                ('totalamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paymentmethod', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollDeductions',
            fields=[
                ('deductionid', models.AutoField(primary_key=True, serialize=False)),
                ('deductiontype', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateofdeduction', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll_deductions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permissionid', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('accesslevel', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsServices',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitCalculations',
            fields=[
                ('profitid', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('totalincome', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('totalexpenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('netprofit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profit_calculations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('poitemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'purchase_order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('purchaseorderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, null=True)),
                ('totalamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'purchase_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteItems',
            fields=[
                ('quoteitemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quote_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quoteid', models.AutoField(primary_key=True, serialize=False)),
                ('quotedate', models.DateField(blank=True, null=True)),
                ('totalamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequisitionItems',
            fields=[
                ('requisitionitemid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('estimatedprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'requisition_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requisitions',
            fields=[
                ('requisitionid', models.AutoField(primary_key=True, serialize=False)),
                ('requestdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requisitions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceBookings',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resource_bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceTickets',
            fields=[
                ('ticketid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('resolutiondetails', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
                ('closedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skillid', models.AutoField(primary_key=True, serialize=False)),
                ('skillname', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('surveyid', models.IntegerField(blank=True, null=True)),
                ('questiontext', models.TextField(blank=True, null=True)),
                ('questiontype', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survey_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponses',
            fields=[
                ('responseid', models.AutoField(primary_key=True, serialize=False)),
                ('responsevalue', models.TextField(blank=True, null=True)),
                ('submittedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survey_responses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskChecklistResults',
            fields=[
                ('resultid', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_checklist_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('duedate', models.DateField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('timetrackingid', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionCategories',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'transaction_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendorid', models.AutoField(primary_key=True, serialize=False)),
                ('vendorname', models.CharField(blank=True, max_length=255, null=True)),
                ('contactperson', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('departmentid', models.ForeignKey(blank=True, db_column='departmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.departments')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('roleid', models.ForeignKey(db_column='roleid', null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.roles')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['username'], name='users_usernam_baeb4b_idx')],
            },
        ),
    ]
